server:
  port: 8381
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 30000ms # 30s

spring:
  profiles:
    active: dev
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: non_null
    default-leniency: true
    # time-zone: GMT+8
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      # 6291456 #文件最大6M，超出5M建议使用切片上传
      max-file-size: 50MB
      # 10485760 # 单个请求最大10M
      max-request-size: 500MB
      enabled: true
  mvc:
    static-path-pattern: /**
  aop:
    proxy-target-class: true
  session:
    timeout: 3600
    store-type: redis
    redis:
      repository-type: default
  web:
    resources:
      static-locations: classpath*:/static,classpath*:/public
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 86400
          cache-public: true
      chain:
        strategy:
          content:
            paths: md5
#  cache:
#    type: caffeine
#    redis:
#      time-to-live: 86400 # 条目过期。默认情况下，条目永不过期。24h
  data:
    redis:
      database: 2
    #    host: 127.0.0.1
    #    port: 31074
    #    password: '123456'
      lettuce:
        pool:
          max-active: 512
          max-wait: 10ms
          max-idle: 100
  #    redisson:
  #      config:
  #        singleServerConfig:
  #          idleConnectionTimeout: 10000
  #          connectTimeout: 10000
  #          timeout: 3000
  #          retryAttempts: 3
  #          retryInterval: 1500
  #          password: null
  #          subscriptionsPerConnection: 5
  #          clientName: null
  #          address: "redis://127.0.0.1:6379"
  #          subscriptionConnectionMinimumIdleSize: 1
  #          subscriptionConnectionPoolSize: 50
  #          connectionMinimumIdleSize: 24
  #          connectionPoolSize: 64
  #          database: 0
  #          dnsMonitoringInterval: 5000
  #        threads: 16
  #        nettyThreads: 32
  #        codec: !<org.redisson.codec.Kryo5Codec> {}
  #        transportMode: "NIO"
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/**/*.xml,classpath*:/META-INF/mapper/**/*.xml
  mapper-locations: classpath:/mapper/**/*.xml,classpath:/mapper/sys/thirdaccount/*.xml



logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level: "%5p"
  config: classpath:logback-default.xml
  level:
    # mybatis-plus 日志
    com.baomidou.example.mapper: info
    com.zxxwl.api.utils.db: debug
    com.zxxwl.test: debug

ueditor: classpath:/static/libs/ueditor/config.json

site:
  title: "小它服务端"

# 自定义参数
custom:
  common-web:
    module-name: login