server:
    port: 9191

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/cp_service?tinyInt1isBit=false&serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
        username: root
        password: 123456
        dbcp2:
            max-idle: 5
            max-wait-millis: 2000
            min-idle: 0
    data:
      redis:
        host: 127.0.0.1
        password: '123456'
        database: 2
        port: 6379

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

file:
    path: /home/java
    magick: